---
name: Release
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'ci'
    branches:
      - release/*
jobs:
  print-debug-info:
    name: Print debug info for Release workflow
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2

  release-dependent-repositories:
    name: Release dependent repositories
    uses: NikitaSkrynnik/.github/.github/workflows/release-dependent-repositories.yaml@get-tag
    with:
      dependent_repositories: "sdk"
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
